### ISSUE TITLE
create primitive set mapping name clash

### ISSUE THREAD

**Issue by DYSIM** [dso-org/deep-symbolic-optimization#74]
in the create primitive set  function below, there seems to be a possibility of mapping name clash.

e.g. If len(lib.input_tokens) == 2, the integer 0 and 1 will be used to rename ARG0 and ARG1.

Further down, if index 0 and 1  of lib.tokens have arity > 0, they will be added to the pset with addPrimitive using 0 and 1 as name as well. Thus it overwrites the previous input_tokens.

Could you confirm if this happens, or am I missing something. Thanks!

```
def create_primitive_set(lib):
    """Create a DEAP primitive set from a dso.libraryLibrary."""

    pset = gp.PrimitiveSet("MAIN", len(lib.input_tokens))
    rename_kwargs = {"ARG{}".format(i): i for i in range(len(lib.input_tokens))}
    for k, v in rename_kwargs.items():

        # pset.renameArguments doesn't actually rename the Primitive.
        # It just affects the pset mapping. So, rename the primitive here.
        pset.mapping[k].name = v

    pset.renameArguments(**rename_kwargs)

    for i, token in enumerate(lib.tokens):
        # Primitives MUST have arity > 0. Deap will error out otherwise. 
        if token.arity > 0:
            pset.addPrimitive(None, token.arity, name=i)

.....

```

**Comment by brendenpetersen** [comment]
I agree some primitives and input tokens (i.e., terminals) will have the same DEAP name for the reason you described. But I believe that DEAP differentiates between primitives and terminals. Namely, they use separate dictionaries, so it should be okay and there should not be any actual collisions of tokens. See https://github.com/DEAP/deap/blob/master/deap/gp.py.

Pretty sure this would break all the GP code if it tokens were actually colliding :P But let me know if you see any behavior issues!

**Comment by DYSIM** [comment]
I see, I printed out pset.mapping before and after  .addPrimitive is called, seems like the Terminals and Primitives are both in the same pset.mapping and overwritten when same name is used.
